[package]
name = "httpmock"
version = "0.5.3-alpha.0"
authors = ["Alexander Liesenfeld <alexander.liesenfeld@outlook.com>"]
edition = "2018"
description = "HTTP mocking library for Rust"
readme = "README.md"
keywords = ["http", "mock", "test"]
categories = ["development-tools::testing"]
license = "MIT"
repository = "https://github.com/alexliesenfeld/httpmock"

[dependencies]
serde = { version = "1.0.117", features = ["derive"] }
serde_json = "1.0.59"
serde_regex = "1.1.0"
lazy_static = "1.4.0"
hyper = "0.13.8"
tokio = { version = "0.2.22", features = ["rt-core", "rt-util", "sync", "macros"] }
base64 = "0.13.0"
regex = "1.4.1"
log = "0.4.11"
qstring = "0.7.2"
assert-json-diff = "1.1.0"
async-trait = "0.1.41"
puddle = "0.1.0"
crossbeam-utils = "0.8.0"
futures-util = "0.3.7"
isahc = "0.9.10"
basic-cookies = "0.1.4"
difference = "2.0"
levenshtein = "1.0.4"

colored = { version = "2.0.0", optional = true }
structopt = { version = "0.3.20", optional = true }
env_logger = { version = "0.8.1", optional = true }

[dev-dependencies]
env_logger = "0.8.1"
tokio-test = "0.2.1"
async-std = { version = "1.6.5", features = ["attributes", "unstable"] }
isahc = { version = "0.9.10", features = ["json"] }
syn = { version = "1.0.48", features = ["full"] }
quote = "1.0.7"
actix-rt = "1.1.1"
colored = "2.0.0"

[features]
standalone = ["structopt", "env_logger"]
color = ["colored"]

[[bin]]
name = "httpmock"
required-features = ["standalone"]
