[package]
name = "httpmock"
version = "0.3.5"
authors = ["Alexander Liesenfeld <alexander.liesenfeld@outlook.com>"]
edition = "2018"
description = "an HTTP mock server library for your tests"
readme = "README.md"
keywords = ["http", "mock", "test"]
categories = ["development-tools::testing"]
license = "MIT"
repository = "https://github.com/alexliesenfeld/httpmock"

[dependencies]
serde = { version = "1.0.112", features = ["derive"] }
serde_json = "1.0.55"
serde_regex = "1.0.0"
regex = "1.3.9"
lazy_static = "1.4.0"
futures = "0.3.5"
hyper = "0.13.6"
tokio = { version = "0.2.21", features = ["rt-core", "rt-util", "sync"] }
log = "0.4.8"
qstring = "0.7.2"
assert-json-diff = "1.0.3"
async-std = "1.6.1"

structopt = { version = "0.3.15", optional = true }
env_logger = { version = "0.7.1", optional = true }

[features]
standalone = ["structopt", "env_logger"]

[[bin]]
name = "httpmock"
required-features = ["standalone"]

[dev-dependencies]
reqwest = { version = "0.10.6", features = ["blocking", "json"] }
env_logger = "0.7.1"
