[package]
name = "mokka"
version = "0.1.0"
authors = ["Alexander Liesenfeld <alexander.liesenfeld@outlook.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.101", features = ["derive"] }
serde_json = "1.0.40"
reqwest = "0.9.20"
lazy_static = "1.4.0"
typed-builder = "0.3.0"
actix-web = "1.0.7"
log = "0.4.8"
simple_logger = "1.3.0"
futures = "0.1.29"
structopt = "0.3.1"

[dev-dependencies]
actix-http = "0.2.10"