[package]
name = "httpmock"
version = "0.5.4"
authors = ["Alexander Liesenfeld <alexander.liesenfeld@outlook.com>"]
edition = "2018"
description = "HTTP mocking library for Rust"
readme = "README.md"
keywords = ["http", "mock", "test"]
categories = ["development-tools::testing"]
license = "MIT"
repository = "https://github.com/alexliesenfeld/httpmock"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_regex = "1.1"
lazy_static = "1.4"
hyper = { version = "0.14", features = ["server", "http1", "tcp"] }
tokio = { version = "1.0", features = ["sync", "macros", "rt-multi-thread"] }
isahc = "1.0"
base64 = "0.13"
regex = "1.4"
log = "0.4"
qstring = "0.7"
assert-json-diff = "1.1"
async-trait = "0.1"
async-object-pool = "0.1"
crossbeam-utils = "0.8"
futures-util = "0.3"
basic-cookies = "0.1"
difference = "2.0"
levenshtein = "1.0"

colored = { version = "2.0", optional = true }
structopt = { version = "0.3", optional = true }
env_logger = { version = "0.8", optional = true }

[dev-dependencies]
env_logger = "0.8"
tokio-test = "0.4"
async-std = { version = "1.8", features = ["attributes", "unstable"] }
isahc = { version = "1.0", features = ["json"] }
syn = { version = "1.0", features = ["full"] }
quote = "1.0"
actix-rt = "2.0.0-beta"
colored = "2.0"

owning_ref = "0.4.1"

[features]
standalone = ["structopt", "env_logger"]
color = ["colored"]

[[bin]]
name = "httpmock"
required-features = ["standalone"]
