[package]
name = "httpmock"
version = "0.3.0"
authors = ["Alexander Liesenfeld <alexander.liesenfeld@outlook.com>"]
edition = "2018"
description = "an HTTP mock server library for your tests"
readme = "README.md"
keywords = ["http", "mock", "test"]
categories = ["development-tools::testing"]
license = "MIT"
repository = "https://github.com/alexliesenfeld/httpmock"

[dependencies]
serde = { version = "1.0.101", features = ["derive"] }
serde_json = "1.0.40"
serde_regex = "0.4.0"
regex = "1.3.1"
lazy_static = "1.4.0"
futures = "0.1.29"
hyper = "0.12.35"
tokio = "0.1.14"
log = "0.4.8"
qstring = "0.7.0"
assert-json-diff = "1.0.0"
httpmock-macros = { path = "./lib/macros", version = "0.1.0"}

structopt = {version = "0.3.1", optional = true }
env_logger = {version = "0.6.2", optional = true }

[features]
standalone = ["structopt", "env_logger"]

[[bin]]
name = "httpmock"
required-features = ["standalone"]

[dev-dependencies]
reqwest = "0.9.20"
env_logger = "0.6.2"

[workspace]
members = [
  "lib/macros"
]