[package]
name = "httpmock"
version = "0.5.3"
authors = ["Alexander Liesenfeld <alexander.liesenfeld@outlook.com>"]
edition = "2018"
description = "HTTP mocking library for Rust"
readme = "README.md"
keywords = ["http", "mock", "test"]
categories = ["development-tools::testing"]
license = "MIT"
repository = "https://github.com/alexliesenfeld/httpmock"

[dependencies]
serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0.61"
serde_regex = "1.1.0"
lazy_static = "1.4.0"
hyper = "0.14.2"
tokio = { version = "1.0.1", features = ["sync", "macros"] }
base64 = "0.13.0"
regex = "1.4.2"
log = "0.4.11"
qstring = "0.7.2"
assert-json-diff = "1.1.0"
async-trait = "0.1.42"
async-object-pool = "0.1.4"
crossbeam-utils = "0.8.1"
futures-util = "0.3.8"
isahc = "1.0.2"
basic-cookies = "0.1.4"
difference = "2.0.0"
levenshtein = "1.0.4"

colored = { version = "2.0.0", optional = true }
structopt = { version = "0.3.21", optional = true }
env_logger = { version = "0.8.2", optional = true }

[dev-dependencies]
env_logger = "0.8.2"
tokio-test = "0.4.0"
async-std = { version = "1.8.0", features = ["attributes", "unstable"] }
isahc = { version = "1.0.2", features = ["json"] }
syn = { version = "1.0.58", features = ["full"] }
quote = "1.0.8"
actix-rt = "2.0.0-beta.1"
colored = "2.0.0"

[features]
standalone = ["structopt", "env_logger"]
color = ["colored"]

[[bin]]
name = "httpmock"
required-features = ["standalone"]
