[package]
name = "mocha"
version = "0.1.1"
authors = ["Alexander Liesenfeld <alexander.liesenfeld@outlook.com>"]
edition = "2018"
description = "an HTTP mock server library for your tests"
readme = "README.md"
keywords = ["http", "mock", "test"]
categories = ["development-tools::testing"]
license = "MIT"
repository = "https://github.com/alexliesenfeld/mocha"

[dependencies]
serde = { version = "1.0.101", features = ["derive"] }
serde_json = "1.0.40"
reqwest = "0.9.20"
lazy_static = "1.4.0"
typed-builder = "0.3.0"
actix-web = "1.0.7"
log = "0.4.8"
futures = "0.1.29"
structopt = "0.3.1"
env_logger = "0.6.2"

[dev-dependencies]
actix-http = "0.2.10"