[package]
name = "httpmock"
version = "0.5.0"
authors = ["Alexander Liesenfeld <alexander.liesenfeld@outlook.com>"]
edition = "2018"
description = "HTTP mocking library for Rust"
readme = "README.md"
keywords = ["http", "mock", "test"]
categories = ["development-tools::testing"]
license = "MIT"
repository = "https://github.com/alexliesenfeld/httpmock"

[dependencies]
serde = { version = "1.0.112", features = ["derive"] }
serde_json = "1.0.57"
serde_regex = "1.1.0"
base64 = "0.12.3"
regex = "1.3.9"
lazy_static = "1.4.0"
hyper = "0.13.8"
tokio = { version = "0.2.22", features = ["rt-core", "rt-util", "sync", "macros"] }
log = "0.4.11"
qstring = "0.7.2"
assert-json-diff = "1.1.0"
async-trait = "0.1.40"
puddle = "0.1.0"
crossbeam-utils = "0.7.2"
futures-util = "0.3.5"
isahc = "0.9.8"
basic-cookies = "0.1.3"
difference = "2.0"
levenshtein = "1.0.4"

structopt = { version = "0.3.17", optional = true }
env_logger = { version = "0.7.1", optional = true }

[dev-dependencies]
env_logger = "0.7.1"
tokio-test = "0.2.1"
async-std = { version = "1.6.4", features = ["attributes", "unstable"] }
isahc = {version = "0.9.8", features = [ "json"] }
syn = { version = "1.0.41", features = ["full"] }
quote = "1.0.7"
httpmock-macros = { path = "./lib/macros", version = "0.4.0" }
actix-rt = "1.1.1"
colored = "2.0.0"

[features]
standalone = ["structopt", "env_logger"]

[[bin]]
name = "httpmock"
required-features = ["standalone"]

[workspace]
members = [
  "lib/macros"
]
