[package]
name = "httpmock"
version = "0.4.3"
authors = ["Alexander Liesenfeld <alexander.liesenfeld@outlook.com>"]
edition = "2018"
description = "HTTP mocking library for Rust"
readme = "README.md"
keywords = ["http", "mock", "test"]
categories = ["development-tools::testing"]
license = "MIT"
repository = "https://github.com/alexliesenfeld/httpmock"

[dependencies]
serde = { version = "1.0.112", features = ["derive"] }
serde_json = "1.0.55"
serde_regex = "1.0.0"
regex = "1.3.9"
lazy_static = "1.4.0"
hyper = "0.13.6"
tokio = { version = "0.2.21", features = ["rt-core", "rt-util", "sync", "macros"] }
log = "0.4.8"
qstring = "0.7.2"
assert-json-diff = "1.0.3"
async-trait = "0.1.36"
puddle = "0.1.0"
crossbeam-utils = "0.7.2"
futures-util = "0.3.5"
isahc = "=0.9.5"

structopt = { version = "0.3.15", optional = true }
env_logger = { version = "0.7.1", optional = true }

[dev-dependencies]
env_logger = "0.7.1"
tokio-test = "0.2.1"
async-std = { version = "=1.6.2", features = ["attributes", "unstable"] }
isahc = {version = "=0.9.5", features = [ "json"] }
syn = { version = "1.0.5", features = ["full"] }
quote = "1.0.2"
httpmock-macros = { path = "./lib/macros", version = "0.3.0" }
actix-rt = "1.1.1"

[features]
standalone = ["structopt", "env_logger"]

[[bin]]
name = "httpmock"
required-features = ["standalone"]

[workspace]
members = [
  "lib/macros"
]
