[package]
name = "httpmock"
version = "0.1.0"
authors = ["Alexander Liesenfeld <alexander.liesenfeld@capgemini.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
structopt = "0.2"
typed-builder = "0.3"
hyper = "0.12"
log = "0.4"
simple_logger = "1.3"
futures = "0.1"
regex = "1"