[remote]
features = "remote,proxy,http2,record,cookies"
release = false

[standalone]
features = "standalone,color,cookies,proxy,record,http2"
release = true

[report]
coveralls = "coveralls_key"
out = ["Html", "Xml"]
