on: push

name: Build

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust:
          # Default features enabled
          - version: stable
          - version: beta
          - version: nightly
          - version: 1.65.0
          # Also remote feature enabled
          - version: stable
            features: remote
          - version: beta
            features: remote
          - version: nightly
            features: remote
          - version: 1.70.0
            features: remote

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust.version }}
          override: true
          components: rustfmt, clippy

      - name: Set feature arguments
        id: set_features
        run: |
          if [ "${{ matrix.rust.features }}" == "remote" ]; then
            echo "::set-output name=FEATURES_ARGS::--features remote"
          else
            echo "::set-output name=FEATURES_ARGS::"
          fi

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: ${{ steps.set_features.outputs.FEATURES_ARGS }}

      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: ${{ steps.set_features.outputs.FEATURES_ARGS }}

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build development version
        if: github.ref != 'refs/heads/master'
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: alexliesenfeld/httpmock:latest
      - name: Build and push
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: alexliesenfeld/httpmock:latest