on:
  push:
    tags:
      - 'v*.*.*'

name: Docker

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Write release version
        run: |
          GITHUB_RELEASE_VERSION=${{ env.RELEASE_VERSION }}
          DOCKER_IMAGE_VERSION="${GITHUB_RELEASE_VERSION#v}"
          echo "GitHub Version: ${GITHUB_RELEASE_VERSION}"
          echo "Docker Version: ${DOCKER_IMAGE_VERSION}"
          echo "DOCKER_IMAGE_VERSION=${DOCKER_IMAGE_VERSION}" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: alexliesenfeld/httpmock:${{ env.DOCKER_IMAGE_VERSION }}
